// Code generated by protoc-gen-go. DO NOT EDIT.
// source: brpc.proto

package brpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SysError struct {
	Errcode              *int32   `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg               *string  `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysError) Reset()         { *m = SysError{} }
func (m *SysError) String() string { return proto.CompactTextString(m) }
func (*SysError) ProtoMessage()    {}
func (*SysError) Descriptor() ([]byte, []int) {
	return fileDescriptor_brpc_aa75679937c0bf94, []int{0}
}
func (m *SysError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysError.Unmarshal(m, b)
}
func (m *SysError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysError.Marshal(b, m, deterministic)
}
func (dst *SysError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysError.Merge(dst, src)
}
func (m *SysError) XXX_Size() int {
	return xxx_messageInfo_SysError.Size(m)
}
func (m *SysError) XXX_DiscardUnknown() {
	xxx_messageInfo_SysError.DiscardUnknown(m)
}

var xxx_messageInfo_SysError proto.InternalMessageInfo

func (m *SysError) GetErrcode() int32 {
	if m != nil && m.Errcode != nil {
		return *m.Errcode
	}
	return 0
}

func (m *SysError) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

var E_CmdID = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         2000000,
	Name:          "brpc.CmdID",
	Tag:           "varint,2000000,opt,name=CmdID",
	Filename:      "brpc.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         2000003,
	Name:          "brpc.Method",
	Tag:           "bytes,2000003,opt,name=Method",
	Filename:      "brpc.proto",
}

var E_Path = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         2000004,
	Name:          "brpc.Path",
	Tag:           "bytes,2000004,opt,name=Path",
	Filename:      "brpc.proto",
}

func init() {
	proto.RegisterType((*SysError)(nil), "brpc.SysError")
	proto.RegisterExtension(E_CmdID)
	proto.RegisterExtension(E_Method)
	proto.RegisterExtension(E_Path)
}

func init() { proto.RegisterFile("brpc.proto", fileDescriptor_brpc_aa75679937c0bf94) }

var fileDescriptor_brpc_aa75679937c0bf94 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2a, 0x2a, 0x48,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0xa5, 0x5c, 0xd2, 0x33, 0x4b, 0x32,
	0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0xd3, 0xf3, 0x73, 0x12, 0xf3, 0xd2, 0xf5, 0xc1, 0xd2,
	0x49, 0xa5, 0x69, 0x10, 0x46, 0xb2, 0x6e, 0x7a, 0x6a, 0x9e, 0x6e, 0x7a, 0xbe, 0x7e, 0x4a, 0x6a,
	0x71, 0x72, 0x51, 0x66, 0x41, 0x49, 0x7e, 0x11, 0x12, 0x13, 0x62, 0x96, 0x92, 0x0d, 0x17, 0x47,
	0x70, 0x65, 0xb1, 0x6b, 0x51, 0x51, 0x7e, 0x91, 0x90, 0x04, 0x17, 0x7b, 0x6a, 0x51, 0x51, 0x72,
	0x7e, 0x4a, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x8c, 0x2b, 0x24, 0xc6, 0xc5, 0x96,
	0x5a, 0x54, 0x94, 0x5b, 0x9c, 0x2e, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe5, 0x59, 0x99,
	0x71, 0xb1, 0x3a, 0xe7, 0xa6, 0x78, 0xba, 0x08, 0xc9, 0xe9, 0xa5, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4,
	0xea, 0xc1, 0x9c, 0xa0, 0xe7, 0x9b, 0x5a, 0x92, 0x91, 0x9f, 0xe2, 0x5f, 0x50, 0x92, 0x99, 0x9f,
	0x57, 0x2c, 0xd1, 0xd0, 0x59, 0x05, 0x36, 0x11, 0xa2, 0xdc, 0xca, 0x82, 0x8b, 0x0d, 0x22, 0x4f,
	0x50, 0x63, 0x33, 0x58, 0x23, 0x67, 0x10, 0x54, 0xbd, 0x95, 0x09, 0x17, 0x4b, 0x40, 0x62, 0x49,
	0x06, 0x41, 0x7d, 0x2d, 0x50, 0x7d, 0x60, 0xd5, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x19,
	0xe0, 0x6e, 0x3e, 0x01, 0x00, 0x00,
}
